### ISSUE TITLE
[Feature]: Caching Functionality

### ISSUE THREAD

**Issue by iinsertNameHere** [iinsertNameHere/catnap#102]
### Is your feature request related to a problem? Please describe:
Some stats are very Resource Intensive and take a lot longer to load then others

### Describe the solution you'd like:
Implement a Caching functionality so that the CPU stat for example, isn't fetched every time but only when explicitly reloading the Cache.

### Additional context:
Would also be useful to add cmd args for re-fetching the cache or for deleting it..

**Comment by yuki-was-taken** [comment]
I think that the cache file should be in `$XDG_CACHE_HOME/catnap/` or `~/.cache/catnap/`, along with all files that right now go in `/tmp/catnap/`

**Comment by yuki-was-taken** [comment]
Also I think that there should be an option like `--no-cache` so that catnap doesn't read the cache and also doesn't cache anything.
