### ISSUE TITLE
[Change]: About the title 

### ISSUE THREAD

**Issue by harbringer-amentiae** [iinsertNameHere/catnap#104]
Hello, this may sound strange, but it's about the title. Catnip is a cool name, but unfortunately it's not original. Here's https://github.com/noriah/catnip project with a similar name and it wouldn't be a problem if it wasn't a terminal sound visualiser application. So because of the same names it is impossible to run the application normally in terminal (if both are present in the system). Moreover, for example yay in Arch, thinks that your catnip-git application package conflicts with the catnip visualiser package, so it suggests replacing one with the other and nothing works. I'm not urging you to change the name, but maybe it's worth contacting the developer of the other application and negotiating this? And then we will get two really cool terminal applications.

**Comment by iinsertNameHere** [comment]
@harbringer-amentiae Hey, I know.
I am actually searching for a new Name for some time now. I will change it when I have a good idea for a new one.

If you have any good Name ideas, feel free to write them here!

**Comment by iinsertNameHere** [comment]
@harbringer-amentiae Hey, I know.
I am actually searching for a new Name for some time now. I will change it when I have a good idea for a new one.

If you have any good Name ideas, feel free to write them here!

**Comment by harbringer-amentiae** [comment]
Oh, thanks for the quick reply. I am not a master of naming, and English is not my main language, but I will suggest a few options. The simplest one is "Catfetch", captures the essence of the programme and keeps the theme of cats. You can also keep the name, but make a reference to the programming language "Catnim". And also variants that have some meaning, but seem funny to me: "Catnap" and "Catlap".

**Comment by iinsertNameHere** [comment]
Thx for the suggestions!

**Comment by Zachmd14** [comment]
agree on this, wanted to use this app because it look really good, but its unfortunately in conflict with the catnip visualizer that I already have installed. 
'Catnap' is a cool name btw :)

**Comment by iinsertNameHere** [comment]
I think “catfetch” is quite good, but I had the idea of ​​simply mixing the two words and making “Catch” out of it. I would appreciate feedback :)

**Comment by iinsertNameHere** [comment]
I think “catfetch” is quite good, but I had the idea of ​​simply mixing the two words and making “Catch” out of it. I would appreciate feedback :)

**Comment by Zachmd14** [comment]
Yep, both sounds good. It's up to you now ;)

**Comment by xzi** [comment]
I vote for either Catfetch or Catnip. Ball is in iinsert's court tho

**Comment by iinsertNameHere** [comment]
Okay, I finally decided on “catnap”. It is closest to the original. I will carry out the renaming process later today. Thx for the Help with finding a new Name!

**Comment by Zachmd14** [comment]
Alright, that's a cool name ! Also cool that we can now have both the sound visualizer and your app at the same time !
Do you mind if I make a post on r/unicorn so people are up to date ?

**Comment by Zachmd14** [comment]
UNIX porn not unicorn, thanks phone

**Comment by iinsertNameHere** [comment]
@Zachmd14  Feel free to make a post! :)
Thx

**Comment by yuki-was-taken** [comment]
I'll rename the AUR package.

**Comment by Zachmd14** [comment]
Cool, thank u

**Comment by yuki-was-taken** [comment]
Okay, it's been updated to `catnap-git`.

AUR link: https://aur.archlinux.org/packages/catnap-git

**Comment by yuki-was-taken** [comment]
![20240607_09h55m45s_grim](https://github.com/iinsertNameHere/catnap/assets/141553384/4bb5c19e-fe5a-49db-aace-daa108f56810)
@iinsertNameHere can you change the URL here to the new one? Thanks.
