### ISSUE TITLE
[Bug]: Desktop is misspelled as "desktp"

### ISSUE THREAD

**Issue by bearfm** [iinsertNameHere/catnap#110]
### What version of Catnap are you running?
Not applicable, considering the typo is present in repo.

### Describe the bug:
In config/config.toml, desktop is misspelled as "desktp". 

### Screenshots:
N/A

### Device:
 - OS: NixOS
 - WM: KDE Plasma 6
 - TERMINAL: Alacritty

### Additional context:
N/A

**Comment by iinsertNameHere** [comment]
Thx :)
