### ISSUE TITLE
[Change]: Alternative to fetching WM information

### ISSUE THREAD

**Issue by Gaabbu** [iinsertNameHere/catnap#112]
### Is your change request related to a problem? Please describe:
I'm not sure how hard it's to implement a way to reliably fetch desktop, but looking at environment variable didn't work in my situation, since I've ran into the problem of it being empty and consequently being set to "Unknown".

### Describe what you want to change:
Don't rely only on ENVs for fetching desktop/wm. Maybe an alternative could be parsing info from /proc/(wm pid)/cmdline.

### Additional context:
I've taken a look at fastfetch, I'm in no capacity able to reliably understand the code, but inside /proc, if you find the pid for the window manager, and checking the file cmdline, it'll output the wm you're using.
![image](https://github.com/iinsertNameHere/catnap/assets/64439196/5f27c759-4ddc-4289-b044-c7f834041fc3)
![image](https://github.com/iinsertNameHere/catnap/assets/64439196/c12b4d9d-731c-46b7-b51c-7a823e57b569)

Extra:
Empty $XDG_SESSION_DESKTOP
![image](https://github.com/iinsertNameHere/catnap/assets/64439196/9b877d02-cfb5-4db7-9fc1-30271e29245a)

Manually set $XDG_SESSION_DESKTOP
![image](https://github.com/iinsertNameHere/catnap/assets/64439196/f3494e8b-843a-4c3b-8f84-67769dce85cb)

**Comment by iinsertNameHere** [comment]
Hey, I will take a look!

**Comment by yuki-was-taken** [comment]
This doesn't work well.
Concatnating the file `cmdline` will just display the command used to launch the program.

Example:
I use `dwl -s autostart` to launch an autostart script along with dwl. When concatnating the `cmdline file`, this is the output:
```bash
$ cat /proc/2929/cmdline
dwl-sautostart$ 
```
As you can see if you use any other options when starting up your WM/DE, it will be in the `cmdline` file as well.

**Comment by Gaabbu** [comment]
I see. Maybe there's some options to go around this.

**Could do:**
_Sanitize the output, strip away launch options_
**and/or**
_Create a dictionary of most used WM/DE, check against it's entries to get the most similar result, and output that._

I understand that it might come with its own set of issues, and there might be a nicer way to check it. But it's a fallback when there's empty env variables, and it might be a good enough way to do that.

**Comment by iinsertNameHere** [comment]
Hey I think it is possible to implement this as a fallback. I will also create a Script which checks if  the XDG vars are set.

**Comment by yuki-was-taken** [comment]
By right `XDG_CURRENT_DESKTOP` should be set, but sway refuses to do so. (And by extension swayfx in your case.) See https://github.com/swaywm/sway/pull/4876#issuecomment-570790128

`XDG_SESSION_DESKTOP` is set by systemd, but you obviously do not have that since you're on Void. See https://gitlab.gnome.org/GNOME/gtk/-/issues/1224#note_270915

`DESKTOP_SESSION` is a legacy variable and it's not commonly set by anyone.

I think the best solution in this case is to just set `XDG_CURRENT_DESKTOP` manually, and I will implement error checking to suggest that the user do this.
