### ISSUE TITLE
[Bug]: Disks doesn't show right stats

### ISSUE THREAD

**Issue by Ryuushen** [iinsertNameHere/catnap#114]
### What version of Catnap are you running?
Commit d48a8303141d75928f651736b458e137f79e0fe2

### Describe the bug:
I tried to shows 2 different disks but the result always show the exact same home disks instead

### Screenshots:
![Uploading 2024-06-27T19_36_14,096064251-07_00.png…]()

### Device:
 - OS: Archlinux
 - WM: Hyprland
 - TERMINAL: Kitty, Fish shell

**Comment by yuki-was-taken** [comment]
I can't see the image, are you sure it's uploaded properly?

**Comment by Ryuushen** [comment]
> I can't see the image, are you sure it's uploaded properly?

Sorry what about this
![1719736319](https://github.com/iinsertNameHere/catnap/assets/24853902/a2c91e60-0450-4a9f-b430-65166f31a65f)

**Comment by iinsertNameHere** [comment]
@Ryuushen  Try now

**Comment by Ryuushen** [comment]
> @Ryuushen Try now

Works perfectly now!
