### ISSUE TITLE
[Feature]: Battery information

### ISSUE THREAD

**Issue by fluffeon** [iinsertNameHere/catnap#115]
### Is your feature request related to a problem? Please describe:
This is not really a problem nor is it really obligatory, this is just a suggestion.

### Describe the solution you'd like:
Basically, a battery indicator under one of the rows on this fetch that shows battery percentage (Maybe also battery status? Like charging and etc). It should probably also account for other nuances like backup batteries, no batteries present (meaning this row would be hidden) or other batteries on the device.

### Additional context:
N/A

**Comment by yuki-was-taken** [comment]
I have an implementation of this stat <https://github.com/yuki-was-taken/catnap/tree/battery> but I'm not sure how handle multiple batteries. This implementation just reads from `/sys/class/power_supply/BAT0`, the folder for the default battery. Catnip's way of working limits me from putting a battery configuration option in `config.toml` (at least I think so). A way of handling multiple batteries is by reading from an environment variable.

**Comment by fluffeon** [comment]
You are awesome.

**Comment by iinsertNameHere** [comment]
I also added that not just BAT0 is checked, but the battery with the lowest number. On my laptop, for example, there is no BAT0 but only BAT1. This works now too.
