### ISSUE TITLE
[Feature]: Custom Figlet Logos

### ISSUE THREAD

**Issue by adjxst** [iinsertNameHere/catnap#116]
Add the option to add custom text as the Figlit Logo.

**Comment by iinsertNameHere** [comment]
Good idea. For now you can just use "-d {custom text}"

**Comment by yuki-was-taken** [comment]
I guess this *could* be done by removing this from `fetch.nim`...
```nim
            if not config.distroart.contains(distroId):
                distroId = "default"
```
