### ISSUE TITLE
[Feature]: Script which checks if the XDG vars are set on install

### ISSUE THREAD

**Issue by iinsertNameHere** [iinsertNameHere/catnap#118]
### Is your feature request related to a problem? Please describe:
#112 

### Describe the solution you'd like:
A script which checks if the XDG vars are set on install. If not, it should walk the user through the process of setting them.

### Additional context:
Nop

**Comment by yuki-was-taken** [comment]
I think this is unneeded. `XDG_CURRENT_DESKTOP` should be set by default, and most (if not all) DEs set it. However, WMs like Sway refuse to set it. (see my comment at #112) I'm in favour of putting a note in the documentation to tell users to manually set `XDG_CURRENT_DESKTOP` if the desktop stat returns "Unknown" for them.
