### ISSUE TITLE
[Question] BSD support?

### ISSUE THREAD

**Issue by fluffeon** [iinsertNameHere/catnap#120]
### Ask your Question:
Is it a possibility that there might be support for BSD systems like FreeBSD, OpenBSD or NetBSD? (I'm personally using FreeBSD now)
I could help troubleshoot.

### Additional context:
![support](https://github.com/iinsertNameHere/catnap/assets/69437909/adf97001-0fac-4d50-965b-1d3108223722)

**Comment by iinsertNameHere** [comment]
Hey, BSD support is a good idea. I don't know any thing about BSD unfortunately. Give me some time to familiarize myself with it a little.
