### ISSUE TITLE
[Question]:does this work on macos

### ISSUE THREAD

**Issue by Itstatertots** [iinsertNameHere/catnap#124]
i tried to install on mac os and when i ran catnip it gave me "Error: unhandled exception: cannot open: /etc/os-release [IOError]"

**Comment by yuki-was-taken** [comment]
This is a problem with getting the distro name on MacOS. /etc/os-release is a file usually only included on Linux, so Catnap's method of getting the distro name does not work on MacOS.

Does anyone know of a way to get the OS name without hardcoding it?

**Comment by yuki-was-taken** [comment]
@Itstatertots build and run Catnap from the latest commit, it should work now.
