### ISSUE TITLE
[Bug]: nim install fails to build

### ISSUE THREAD

**Issue by TheHerowither** [iinsertNameHere/catnap#125]
### Describe the bug:
When i try to run nim install it fails with this error:
```sh
home/myname/Documents/tools/catnap/src/catnaplib/platform/fetch.nim(38, 21) template/generic instantiation of `capture` from here
/usr/lib/nim/lib/pure/sugar.nim(234, 11) Error: node lacks field: strVal
```

There is not much more to this, and i can't find out why this happens.

### Device:
 - OS: Kubuntu 24.04 LTS x86_64
 - WM: kwin
 - TERMINAL: Konsole (zsh)

**Comment by yuki-was-taken** [comment]
Can't reproduce, it builds just find for me on a newly cloned repo.

**Comment by TheHerowither** [comment]
Interesting

**Comment by TheHerowither** [comment]
I found a temporary solution, however this fix causes the disk_0 to seg fault.
To fix the issue i had to comment out line 38 thru 40 in `catnap/src/catnaplib/platform/fetch.nim`

**Comment by yuki-was-taken** [comment]
Seems like a problem with the disk stat, specifically getting the mount points.

**Comment by iinsertNameHere** [comment]
I can't reproduce this. This would be helpful to resolve this error
