### ISSUE TITLE
[Question]: How can I install this in Windows?

### ISSUE THREAD

**Issue by lengoc-quang** [iinsertNameHere/catnap#127]
I tried to install Catnap in Windows 11 and when I build, it shows this error:
![image](https://github.com/user-attachments/assets/b8c8cfe6-e150-4583-9903-dfd0b77a16ce)
So I tried to install this in Git Bash and it shows the same.
How can I install this in Windows? Or it is not supported now?

**Comment by iinsertNameHere** [comment]
Windows support was removed with this commit 3fe3e09fcdb65852077c6e9835d270807a1e2c15.
