### ISSUE TITLE
[Question]: Port to Rust?

### ISSUE THREAD

**Issue by iinsertNameHere** [iinsertNameHere/catnap#130]
### Ask your Question:
I am thinking about porting catnap to Rust.
*Pros:*
- More people know rust which means that more people would be able to contribute to the project.
- Rust is faster

*Cons:*
- I don't know rust which means it would take some time.

What do you think about this?

**Comment by apprehensions** [comment]
Nim transpiles to C.

**Comment by iinsertNameHere** [comment]
> Nim transpiles to C. Your project stands out in that it is in Nim. There are hundreds of Rust system fetchers.

Thanks for you Feedback
