### ISSUE TITLE
[Question]:

### ISSUE THREAD

**Issue by spectrum705** [iinsertNameHere/catnap#131]
### Ask your Question:
HI, when i try to open an image in viu it appears blurred and pixalated. I am new to it and i read the docs.
also, the weather widget doesnt seem to work for me.
 can anyone please guide me through?
 Thank you 
### Additional context:
Add any other context or screenshots about the question here.
![image](https://github.com/user-attachments/assets/d3e20086-f123-4b25-b004-e9340189116f)

**Comment by spectrum705** [comment]
and when using with catnap, i dont see the image at all. 
these are my image config

[misc.imageMode] # Requires Viu.
enable = true
path   = "/home/spectrum93/Pictures/Wallpapers/111544382_p0.jpg"# Please only use absolute paths.
scale  = 18
margin = [2,2,3,]

**Comment by yuki-was-taken** [comment]
1. What terminal emulator are you using?
2. In what way does the weather module not work?

**Comment by spectrum705** [comment]
I use the default ubuntu terminal with fish shell but the was same with bash.

and the weather widget started working later on

**Comment by yuki-was-taken** [comment]
From the viu [repo](https://github.com/atanunq/viu):
>It uses either [iTerm](https://iterm2.com/documentation-images.html) or [Kitty](https://sw.kovidgoyal.net/kitty/graphics-protocol.html) graphics protocol, if supported. If not, lower half blocks (▄ or \u2584) are displayed instead.

If iTerm or kitty is not used, then viu will use half blocks to display the image, which results in the pixelated image.
(See also https://github.com/atanunq/viu/issues/83)

**Comment by spectrum705** [comment]
oh okay. thanks.
