### ISSUE TITLE
[Bug]: Processor still references to Celeron G4930 after upgrading to i5-9400

### ISSUE THREAD

**Issue by sech1p** [iinsertNameHere/catnap#135]
### What version of Catnap are you running?
Commit d0e5d55df0812cf5028d553d1324ca68df66fd39

### Describe the bug:
After upgrading to i5-9400 processor, catnap still references it as Celeron G4930 even it is recompiled. Recompilation worked after changing graphic card but nothing is changed after upgrading processor

### Screenshots:
![image](https://github.com/user-attachments/assets/87957298-79a0-4880-8e86-b02fa8f0d270)

### Device:
 - OS: Arch Linux
 - WM: KDE Plasma 6
 - TERMINAL: Konsole

**Comment by iinsertNameHere** [comment]
The Cpu stat is Cached and refreshed automaticly after one day. To force a refresh, run  catnap with the "--no-cache" flag once. This should resolve you issue.

**Comment by sech1p** [comment]
It turns out that my problem has been solved. Thank you
