### ISSUE TITLE
[Question]: Which file does catnap read the system information from?

### ISSUE THREAD

**Issue by Yakumo-Yukari** [iinsertNameHere/catnap#137]
### Ask your Question:

CachyOS is a distribution based on Arch Linux.

I modified the system information in the /etc/os-release and /usr/lib/os-release files of CachyOS, but catnap still displays CachyOS.

### Additional context:
Add any other context or screenshots about the question here.

**Comment by iinsertNameHere** [comment]
Hey try running catnap with the --no-cache flag.
This should resolve the Problem.
