### ISSUE TITLE
[Feature]: Manually define location for weather

### ISSUE THREAD

**Issue by ituri** [iinsertNameHere/catnap#143]
Hi,

Thank you for the recent updates! With the latest commits, catnap is really becoming usable on MacOS—it's much appreciated!

I recently enabled the weather component, but I've noticed that the location it uses is a bit off, showing a city about 80 km away. Would it be possible to add an option to set the location manually? This would allow for more accurate weather information, which would be fantastic.

Thanks again for this wonderful program!

Best,
ituri

**Comment by ruiiiijiiiiang** [comment]
Hi @ituri, I've made the change you requested. Please pull the latest code and add a location value to the misc section of the config (https://github.com/iinsertNameHere/catnap/blob/main/config/config.toml#L37). You should be able to get the weather information for any location you want.

**Comment by ituri** [comment]
Excellent! Working as expected. Thank you!
