### ISSUE TITLE
[Bug]: Build on Debian failing

### ISSUE THREAD

**Issue by ituri** [iinsertNameHere/catnap#150]
I hope it's okay that I'm flooding the repo with issues. ;) See it as an appreciation of catnap; I just like to get it running on all of my systems.

Right now, I have trouble getting catnap to compile on Debian bookworm:
```
➜  catnap git:(main) nim install
Cleaning existing build
Building in release mode
/usr/lib/nim/lib/pure/times.nim(2135, 39) Hint: 'parse' cannot raise 'Defect' [XCannotRaiseY]
stack trace: (most recent call last)
sugar.nim(234, 11)       capture
/home/phil/catnap/src/catnaplib/platform/fetch.nim(38, 25) template/generic instantiation of `capture` from here
/usr/lib/nim/lib/pure/sugar.nim(234, 11) Error: node lacks field: strVal
stack trace: (most recent call last)
/usr/lib/nim/lib/system/nimscript.nim(429, 18)
/home/phil/catnap/config.nims(120, 16) installTask
/home/phil/catnap/config.nims(60, 12) releaseTask
/home/phil/catnap/config.nims(22, 9) compile
/usr/lib/nim/lib/system/nimscript.nim(273, 7) exec
/usr/lib/nim/lib/system/nimscript.nim(273, 7) Error: unhandled exception: FAILED: nim c  --cincludes:/home/phil/catnap/src/extern/headers --path:/home/phil/catnap/src/extern/libraries --passC:-f --mm:arc --threads:on --panics:on --checks:off --verbosity:0 -d:danger --opt:speed -d:strip --outdir:/home/phil/catnap/bin /home/phil/catnap/src/catnap.nim [OSError]
➜  catnap git:(main)
```

Is there anything I can do to fix this error?

**Comment by ruiiiijiiiiang** [comment]
Hi @ituri any feedback is greatly appreciated! The error you're seeing appears to be specific to how your drives are mounted. While we look for a more permanent fix, here's a quick hack you can do to make sure the code compiles.
Comment out the `if` condition [here](https://github.com/iinsertNameHere/catnap/blob/main/src/catnaplib/platform/fetch.nim#L31-L45) and un-indent line 46 and 47, so it looks like this:

![CodeSnap_2024-11-13_at_16:37:24](https://github.com/user-attachments/assets/cafa6a11-006f-4e47-871f-43d081ea8faa)
(notice the indentation on line 46 and 47)
This essentially skips checking for any additional mounted drives besides the root `/` and you should be able to build and run it after this modification.

**Comment by iinsertNameHere** [comment]
Closed as it is not reproducible
