### ISSUE TITLE
[Feature]: arch_old logo

### ISSUE THREAD

**Issue by amberjennings** [iinsertNameHere/catnap#151]
### Is your feature request related to a problem? Please describe:
I'm a big fan of the [old Arch logo](https://archlinux.org/static/logos/legacy/arch-legacy-aqua.5d03b6ac5b5b.svg) which is included in other tools like neofetch as arch_old.

### Describe the solution you'd like:
I tried my hand to create the ascii for it myself and failed miserably so thought to make a feature request - hoping somebody else would be willing to take this on.

### Additional context:
[Large version of old logo as ascii](https://github.com/dylanaraps/neofetch/blob/master/neofetch#L5997)

**Comment by iinsertNameHere** [comment]
![image](https://github.com/user-attachments/assets/0f13fea2-37b1-4108-9571-d6fe98c2414d)

Her is the new arch_old logo.
To use it run `catnap -d arch_old`
