### ISSUE TITLE
[Bug]: Will not launch with no battery in BAT0

### ISSUE THREAD

**Issue by Kazzy705** [iinsertNameHere/catnap#153]
### What version of Catnap are you running?
`Commit 2623f97443b21fae3fd6a2974f6ce3a12d4c6ca6`

### Describe the bug:
My system has two batteries. One of the batteries(BAT0) is unused, as in there is no battery there. There is, however a battery in BAT1. Catnap will not launch.

### Screenshots:
Launching catnap results in:
```
$ catnap

syncio.nim(855)          readFile
Error: unhandled exception: cannot open: /sys/class/power_supply/BAT0/capacity [IOError]
```

### Device:
 - OS: Arch Linux
 - WM: Hyprland
 - TERMINAL: Kitty

**Comment by ruiiiijiiiiang** [comment]
Hi @Kazzy705 please pull the latest code and build again. This issue should have been fixed.
