### ISSUE TITLE
[Question]: What is the default Emoji Font for Weather Icons

### ISSUE THREAD

**Issue by Tamarindtype** [iinsertNameHere/catnap#156]
### Question:
I'm using Noto Color Emoji rn but it does not show up, is there a specific Emoji Font to install or any Emoji Fonts?

### Additional context:
![241205_05h54m48s_screenshot](https://github.com/user-attachments/assets/2a045238-855c-46ee-9fc5-155c8521b30b)

**Comment by iinsertNameHere** [comment]
There is No Default Emoji Font for weather. Just use what font you like. If the Emoji is not Shown, try using a different Font.

**Comment by Tamarindtype** [comment]
> There is No Default Emoji Font for weather. Just use what font you like. If the Emoji is not Shown, try using a different Font.

Okay thanks, I'll try it
